# version: '3'
services:

  burger_order:
    build: "./containers/burger_order/"
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    # volumes:
      # - ./containers/burger_order:/app
  
  kitchen_view:
    build: "./containers/kitchen_view/"
    ports:
      - "5000:5000"
    # volumes:
      # - ./containers/kitchen_view:/app

  mysql:
    build: ./containers/menu_store/
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    # volumes:
      # - db_data:/var/lib/mysql

# volumes:
  # db_data: